#
#  ____                 __        __                 _       _   ____
# |  _ \    ___   _ __  \ \      / /   ___    _ __  | |   __| | / ___|    ___   _ __  __   __   ___   _ __
# | |_) |  / _ \ | '__|  \ \ /\ / /   / _ \  | '__| | |  / _` | \___ \   / _ \ | '__| \ \ / /  / _ \ | '__|
# |  __/  |  __/ | |      \ V  V /   | (_) | | |    | | | (_| |  ___) | |  __/ | |     \ V /  |  __/ | |
# |_|      \___| |_|       \_/\_/     \___/  |_|    |_|  \__,_| |____/   \___| |_|      \_/    \___| |_|
#
# Created by Struck713 (https://www.spigotmc.org/members/struck713.129781/)

options:
  chat:
    enabled: true
  tablist:
    enabled: true
  update-checker:
    enabled: true

messages:
  prefix: '&8[&3PWS&8] &7'
  commands:
    no-console: 'This command cannot be ran from console.'
    no-permission: 'You do not have permission to use this command!'
    help:
      - '&7&m----------------------'
      - '&3&lPerWorldServer'
      - ' '
      - '&7 - &3/pws  &fShows this menu'
      - '&7 - &3/pws reload  &fReloads configurations'
      - '&7 - &3/pws global  &fToggle global chat'
      - '&7 - &3/pws list  &fShows a list of worlds and players.'
      - ' '
      - '&7&m----------------------'
    global:
      toggle:
        true: 'You will now see all chat messages.'
        false: 'You will no longer see all chat messages.'
      format: '&c[%world%] &7<%player%> %message%'
    reload: 'The config has been reloaded!'
    list:
      header: '&3Worlds&7:'
      item: '&7- &e%world%&7: &f%players%'

# DO NOT EDIT
config-version: 3.5